### ISSUE TITLE
Puedes usar return directamente en el selector no hay necesidad de crear una constante

### ISSUE THREAD

**Issue by FabrizioOtranto** [sebadevita/preentrega-pushingit#1]
https://github.com/sebadevita/preentrega-pushingit/blob/1b734906c036c48ae64572116bda5d69865194e1/cypress/support/pages/shoppingCartPage.js#L8

**Comment by sebadevita** [comment]
Joya, me parecia mas claro tener 2 lineas mas cortas pero lo cambio. Gracias!
