### ISSUE TITLE
Crear un metodo que sea para verificar unicamente el nombre del producto

### ISSUE THREAD

**Issue by FabrizioOtranto** [sebadevita/preentrega-pushingit#2]
https://github.com/sebadevita/preentrega-pushingit/blob/1b734906c036c48ae64572116bda5d69865194e1/cypress/support/pages/shoppingCartPage.js#L6

**Comment by sebadevita** [comment]
No entendí muy bien, decis que devuelva el nombre del producto tipo como hice con el precio pasandole por parametro el nombre por ejemplo?

**Comment by FabrizioOtranto** [comment]
Claaro y ene l test validar el producto!

**Comment by sebadevita** [comment]
Ahora entendí lo del metodo pero sería parra agregar una validación que efectivamente se agrego el producto clickeado en el carrito o para que debería usar la función nueva? Es decir agregar en el test algo como esto?

`shoppingCartPage.returnProductName(testData.products.redCap).should('have.text', "Red Cap")
 shoppingCartPage.returnProductName(testData.products.whitePants).should('have.text', "White Pants")`

**Comment by FabrizioOtranto** [comment]
Claaaro seria para eso que pusiste ahi! agrega el metodo en la pagina y luego usalo en el test! (usa el fixture en la asercion en vez de strings)

**Comment by sebadevita** [comment]
perfecto ya mergeado!
